version: '3.5'

services:
    frontend:
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000

    backend:
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        volumes:
            - ./volume:/src/model

    training:
        build: ./ml-kurkkumopo-training
        volumes:
            - ./volume:/src/model/
            - ./:/src/data

volumes:
    backend:
    training:
